# Generated by Django 4.0 on 2022-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='uploads/')),
                ('title', models.CharField(max_length=80)),
                ('sound', models.FileField(upload_to='sounds/')),
            ],
        ),
    ]
